version: '2'
services:
 web:
  build: node:4-onbuild
  volumes:
    - ./app/:/usr/app/src
  command: npm start 
  ports:
    - "5000:5000"
  links:
   - postgres
 tasks:
  build: python:2-onbuild
  volumes:
    - ./backend/:/usr/tasks/src
  links:
    -postgres
    -rabbitmq
  command: python HOBOgrab.py 
#change to celery -A tasks worker 
 postgres:
  image: postgres
   
# use the env
#map or copy into init.d file using volumes, chargepoint
  volumes:
    - ./database/entrypoint:/docker-entrypoint-initdb.d/
  ports:
    - "5432:5432"
 rabbitmq:
  image: rabbitmq 
