version: '2'
services:
 web:
  container_name: web
  build: ./app
  volumes:
    - /app:/usr/app/src
  ports:
    - "3000:3000"
  expose:
    - "3000"
  links:
   - postgres
 tasks:
  container_name: tasks
  image: celery:3.1
  volumes:
    - ./backend/:/usr/tasks/src
  links:
    - postgres
  command: bash -c "python logger_processing".py
 postgres:
  container_name: postgres
  environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=feed
  image: postgres
  volumes:
    - ./database/entrypoint:/docker-entrypoint-initdb.d/
  ports:
    - "5437:5437"
