version: '2'
services:
 web:
  build: .
  volumes:
    - .:/usr/app/src
  command: python /usr/app/src/dashboard/runserver.py
  ports:
    - "5000:5000"
  depends_on:
   - db
   - rabbitmq
 db:
  image: postgres
 rabbitmq:
  image: rabbitmq 
