version: '2'
services:
 web:
  container_name: web
  image: node:4-onbuild
  volumes:
    - ./app/:/usr/app/src
  command: npm start 
  ports:
    - "5000:5000"
  links:
   - postgres
 tasks:
  image: python:2-onbuild
  volumes:
    - ./backend/:/usr/tasks/src
  links:
    - postgres
    - rabbitmq
  command: python HOBOgrab.py 
 postgres:
  container_name: postgres
  environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=feed
  image: postgres
  volumes:
    - ./database/entrypoint:/docker-entrypoint-initdb.d/
  ports:
    - "5432:5432"
 rabbitmq:
  container_name: rabbitmq
  image: rabbitmq 
