version: '2'
services:
 web:
  build: .
  volumes:
    - .:/usr/app/src
  command: python /usr/app/src/dashboard/runserver.py
  ports:
    - "5000:5000"
  links:
   - postgres
   - rabbitmq
 postgres:
  image: postgres
  build: ./database
  ports:
    - "5432:5432"
 rabbitmq:
  image: rabbitmq 
